
require("./lib/bootstrap-tour.js")
require("./lib/numeric-1.2.6.js")

# Ours
require('./print.coffee')
require('./slider.coffee')
require('./gene_table.coffee')
require('./parcoords.coffee')
require('./ma_plot.coffee')
require('./heatmap.coffee')
require('./bargraph.coffee')
require('./scatter3d.coffee')
require('./pca.coffee')
require('./kegg.coffee')
require("./tour.coffee")
require("./edit-list.coffee")
require('./normalize.coffee')
require('./qc.coffee')
require('./gene-expression.coffee')
require('./compare.coffee')
